- platform: xiaomi_cloud_map_extractor
  host: !secret ip_vacuum
  token: !secret vacuum_token
  username: !secret username
  password: !secret xiaomi_psw
  colors:
    color_path: [255, 255, 255]
  draw: ["all"]
  map_transformation:
    scale: 1
    trim:
      top: 20
      bottom: 20
      left: 20
      right: 20
  auto_update: true
  scan_interval:
    seconds: 600 #10minutes
  attributes:
    - calibration_points
